### ISSUE TITLE
Life Support Rebalance

### ISSUE THREAD

**Issue by DanStaal** [DanStaal/DStaal_UKS_KPBS_Addons#1]
The proposed numbers for rebalancing for USI-LS:
https://github.com/ibanix/UKS-KPBS_Compatibility/wiki/USI-LS-Compatibility-(Proposed)

(Compiled by @ibanix )

**Comment by Merkov** [comment]
Quick questions/comment for the stage 2 LS rebalance: how do you want the file structure to look? If we want, we can just do everything in one .cfg file (maybe kept in Parts_Mods for now) which would mean that Nils only has to replace his current one (called KPBS_MM_USI_LS.cfg, so we can even keep the name the same). Does that sound good?

**Comment by Merkov** [comment]
For your life support branch table, I just wanted to record somewhere on GitHub (as opposed to the forums) that for the Mk1 habitat, we came up with a volume of roughly 10.7 m3 (listening to KIS). For that, I found that crew capacity 3, kerbal months 10, and leaving the LS supplies as they are (160 supplies, 75 mulch, 150 EC). The habitat should cost 2.5 EC/s according to the spreadsheet. 

Also, doing some rough measuring, it looks like the planetary greenhouse will have a volume of roughly 25 m3. I figure it's about 1.25 m tall (maybe a bit taller in the middle, maybe a bit shorter at the edges when deployed) and roughly 4 m wide, 5 m long (it's probably a little more than 4 and a little less than 5, respectively, but close enough). That gets me a volume of 25 m3.

**Comment by DanStaal** [comment]
For the LS file structure: Honestly, what I'd like to do is just copy over Nils' file, edit it, and then send it back.  ;)  So yeah, keeping it all in one config sounds good.

And thanks for the dimensions and work on the other parts.  As something that might help with doing some of those conversions, it's worth keeping in mind this graphic:
<http://forum.kerbalspaceprogram.com/index.php?/topic/133606-122-kerbal-planetary-base-systems-v140-1feb17/&do=findComment&comment=2946780>

**Comment by Merkov** [comment]
I actually just started looking for that. Unfortunately, it doesn't really help with many of the other parts, since none of the dimensions on that diagram are shared with other KPBS parts, but I did come up with a volume of about 30 m3, which should be just about right with RoverDude's stuff, since he calls a 3.75 m Tundra 66 m3. This is almost half as tall, and has the same diameter. It loses a bit of volume because of the conical frustum at the top. Another volume statistic for the books!

**Comment by Merkov** [comment]
Okay, going to try building a little table here to keep track of which parts I have figured out and which I have left. This is using the info from a forum post on page 2: 

Part|PartName|Mass|Volume|Seats|Months|Multiplier|EC/s|Recycler %|Spreadsheet Approved?
----|----|----|----|----|----|----|----|----|----
*Air Filter*|*KKAOSS_LS_container_airfilter*|*0.7*|*1.2*|*0*|*n/a*|*n/a*|*n/a*|*n/a*|*no*
Algae Container|KKAOSS_LS_container_algae|0.5|2.4|0|n/a|n/a|n/a|n/a|no
**Carbon Extractor (Air Refresher)**|**KKAOSS_LS_container_carbon_extractor**|**0.5 (modified)**|**1.2**|**0**|**n/a**|**n/a**|**0.8**|**0.4/4**|**close enough**
*Elektron Container*|*KKAOSS_LS_container_elektron*|*0.7*|*?*|*0*|*n/a*|*n/a*|*n/a*|*n/a*|*no*
Greenhouse Container|KKAOSS_LS_container_greenhouse|0.5|2.4|0|n/a|n/a|n/a|n/a|no
*Sabatier Container*|*KKAOSS_LS_container_sabatier*|*0.7*|*?*|*0*|*n/a*|*n/a*|*n/a*|*n/a*|*no*
Water Purifier Container|KKAOSS_LS_container_waterpurifier|0.7|1.2|0|n/a|n/a|1.0 (0.0064 W)|82% (purifier)|yes
Recycler Container|KKAOSS_USI_Recicler_g|0.7|1.2|0|n/a|n/a|1|60/2|no
Greenhouse|KKAOSS_Greenhouse_g|3.0|25|2|0|1.3/2|0.525:1|35/4|no
Central Hub|KKAOSS_Central_Hub|7.5|30|6|0|1.5/6|2.25/19.25 (0.0085 W)|92.5/1|yes-ish
MK2 Habitat|KKAOSS_Habitat_MK2_g|2.6|~14?|4|30/4|1/4|0.7|n/a|no
**MK1 Habitat**|**KKAOSS_Habitat_MK1_g**|**1.7**|**10.7**|**3**|**10**|**0.2/4**|**2.7**|**n/a**|**um...**
Cupola|KKAOSS_Cupola_g|1.75|?|1|0|2/2|0.09|na|no
Science Lab|KKAOSS_Science_g|3.55|?|2|0|1.25|1.2|50/5|no
Recycler|KKAOSS_USI_Recicler_g|3.5|5.4|0|n/a|n/a|6|70%/6|no

Since it looks like you can edit your own comments on issues, I think I'll just keep editing this chart as I go along. I took the liberty of adding a Volume column as well as a Spreadsheet Approved column. Once I've balanced something against the spreadsheet, I'll make everything bold as well. One thing I can't capture here is converters.

**Comment by Merkov** [comment]
I suppose a follow up question to the chart above: are there any parts on that list that shouldn't be in USI-LS? As you mentioned on the forum, not all of these currently show up with USI-LS, but they do with other LS mods. I feel like things like the Elektron container, Sabatier Container, etc. don't really fit with the abstraction level of USI-LS. I wouldn't mind trying to find a fit for the greenhouse container (though I think you already mentioned that retrieving food from a greenhouse on EVA seems a bit... odd...) and maybe even making the Water Purifier work like a USI-LS purifier. If we're really looking to use more of these parts, I suppose something like the Air Filter could be an early, low tech-tree, low efficiency recycler perhaps? 

My thinking is that we can probably do without the Carbon Extractor, Elektron Container, or Sabatier Container, and we probably don't need the Air Filter either. I would like to find a home for the rest of the parts in USI-LS, though.

**Comment by DanStaal** [comment]
The Greenhouse already is in USI-LS - we just need to check the config.  I don't think it should be reconfigurable - just mulch+fert.

I'm using the Sabatier (the model anyway) as a long-range power transceiver.  Let's not confuse people with other uses. ;)   And yes, no need for every part - if you see good fit, fine, but no need to force.  (I like the air filter idea.  Small rate for large crew count?)

Water filter - let's be careful: a small purifier could be op.  High-rate recycler (even using water?) sounds good.

**Comment by Merkov** [comment]
Sorry, I meant that the greenhouse container has a place alongside the full greenhouse, not that it wasn't already used in USI-LS. 
As for the water purifier, I just kind of assumed that any USI recycler that uses water as an input is  called a purifier. It doesn't have to have a crazy high percentage. I thought maybe in the container LS parts, we could have the filter, then the recycler (slightly more efficient) then the purifier. I haven't run the numbers, but the purifier would probably only be around 70% given how light and small those parts are.

**Comment by DanStaal** [comment]
Wanted to be clear on purifier - and terse, so I don't have to painfully type.

Small greenhouse: less production, one mode, (early tech tree?).  Large greenhouse: more production, multi modes possible.

Sounds good.

**Comment by Merkov** [comment]
Got it. I have a bunch of free time over the next few nights, so I'll keep posting stuff here and on the forum as I get to it. Don't feel obligated to respond to anything until your arm is doing better.

**Comment by Merkov** [comment]
I made a quick update to the chart: first, I noticed we had the wrong mass for the USI Recycler Container, so I amended that. I also put all of the parts that I don't think need to be in USI-LS in italics. If nobody has any objections, I'll probably remove them from the list entirely for housekeeping reasons. 

It turns out the air filter uses the same model as the USI Recycler Container, so there's not much point in including both. 

The Water Purifier Container does use a different model (and a pretty nice looking one, too) so I wouldn't mind including it. As an aside, since the KPBS life support containers are so small and dense, they don't play terribly nicely with the spreadsheet. Once you hit the 1.2 cubic metres, you're still a long way away from the 0.7 tonnes of mass. For the following, I'm just getting close and calling it good enough. Here's what I'm thinking: 

The Recycler Container will be the first K&K recycler you get. My chart above must be out of date, because when I look at the part in game, it says it's a 60% recycler for 2 kerbals, costs 1 EC/s. This is actually fairly well balanced. The spreadsheet wants the part to be slightly bigger (1.35 vs 1.2), but a lot lighter (0.2 vs 0.7). 

The Water Purifier has the same size and mass. If we made it an 80% (0.006 Water) or 85% (0.007 Water) purifier for one kerbal (The EC/s cost goes up a lot in that small range: 0.5 EC/s for 80%, 1.75 EC/s for 85%) then it would be roughly balanced (80% is actually smaller and lighter, while 85% is a bit bigger and lighter than balanced, but I'm worried that 85% might be too high...). My thinking is that this could be a slightly later tech tier, only affects 1 kerbal, and uses water, but it can be used to boost a base's max recycling efficiency a bit before you get the really powerful purifier on the central hub. 

I had even debated doing something like making the USI recycling container an even lower recycling percentage (40% or so) but making it affect more kerbals (4). That way, the recycling container gets you a greater supply consumption reduction for a large group of kerbals than the water purifier, but the purifier lets you boost that rate. This actually makes the recycling container overpowered for its size, but still way under for its mass. 

Having said all of that, we don't need to include the water purifier if you don't want it, and we could leave the recycling container exactly how it is and it is as well balanced as it can be (though we could reduce the mass. It looks like Nils makes most of his LS container parts either 0.7 or 0.5 t. This one could afford to be a 0.5 t one, but that's not a huge deal).

**Comment by Merkov** [comment]
Just quickly updated the chart listings for the Carbon Extractor, Water Purifier, and MK1 Habitat. 
Edit: and the Central Hub.

**Comment by Merkov** [comment]
Okay, going to throw a quick table here to compare some USI-LS nom-o-matics so we can see how they compare, plus I threw in a quick idea for the greenhouse and greenhouse container. Since the ratio of Fertilizer:Mulch:Supplies is always 1:10:11 I just put the supplies output numbers on here for now. EC/s for the greenhouse is for agroponics first, hab second. 

Part|PartName|Mass|Volume|Seats|Months|Multiplier|Supplies Rate|EC/s
----|----|----|----|----|----|----|----|----
Nom-O-Matic 5000|USILS_Greenhouse_MiniCupola|0.154|?|0|n/a|n/a|0.000132|0.26
Nom-O-Matic 25000|USILS_Greenhouse_Cupola| 0.708|?|0|n/a|n/a|0.00066|1.32
Nom-O-Matic 25000-I|USILS_Greenhouse_Inline|1.52|18?|2|n/a|n/a|0.00132|2.64
Greenhouse|KKAOSS_Greenhouse_g|3|~21|2|n/a|1x3 kerbals|0.00132|2.64/0.75
Greenhouse Container|KKAOSS_LS_container_greenhouse|0.5|2.4|0|n/a|n/a|0.000495|0.99

Just for fun, I put in the listed conversion numbers into the spreadsheet to see recommended volumes. 
5000: 0.651 (suggested mass lower: 0.13 vs 0.154)
25000: 3.303 (suggested mass is lower: 0.66 vs 0.708)
25000-I: 7.105 (suggested mass exactly 1.52)

The suggestions above make the full sized Greenhouse just as powerful as the 25000-I, but also adds a 1 x 3 kerbal multiplier. This has a suggested mass of 3.02 and a volume of 13.105, which leaves us with a ton of extra volume (although there is a provision to make agriculture-like modules require extra volume. Doing that bumps the volume up to about 25). 

The Greenhouse Container can't really affect hab at all, so I just made it as close to the mass and volume requirements as possible. It's almost perfect, and it comes in just slightly less powerful than the regular 25000. I'm okay with that, since the 25000, being a cupola, actually has a bigger surface area, whereas the Container shape is a little more awkward. 

I'll post the suggestions in their respective parts issues, but I thought being able to see all of them in one place would be handy.

**Comment by DanStaal** [comment]
This was always informational - I'm marking it closed.
