### ISSUE TITLE
Carbon Extractor

### ISSUE THREAD

**Issue by DanStaal** [DanStaal/DStaal_UKS_KPBS_Addons#19]
Config update needed.

Habitation/Recycling Info:

| Part                     | PartName                                   | Mass    | Volume   | Seats | Months | Multiplier | EC/s                  | Recycler % | Spreadsheet Approved? |
|:-------------------------|:-------------------------------------------|---------|----------|-------|--------|------------|-----------------------|------------|-----------------------|
| *Carbon Extractor*       | *KKAOSS\_LS\_container\_carbon\_extractor* | *0.7*   | *?*      | *0*   | *n/a*  | *n/a*      | *n/a*                 | *n/a*      | *no*                  |

**Comment by Merkov** [comment]
Do we want to include the Carbon Extractor? I had put it in italics originally because I didn't think it really fit with USI-LS. I suppose, if it has a different model than all of the other parts so far, we could revive that idea I had (originally with the air filter) of making a really low efficiency, high kerbal count recycler. Honestly, though, since we have one regular recycler container plus one higher efficiency recycler (in the form of the purifier) I don't really know if another container-form factor recycler is needed.

**Comment by DanStaal** [comment]
I don't know if it's needed - but I like having options.  And since it's a different model than anything else, I figure we might as well use it.

As per my note in the recycler issue, I'm thinking we use the 40/4 recycler for this one, maybe drop the mass to 0.5?  (We're basically making a new part using the model, instead of modifying an existing part.)

**Comment by Merkov** [comment]
That sounds good to me. Should we also possibly rename the part, then? The only reason I'm thinking of that is because the name "Carbon Extractor" is far more... specific than any other recycler. I don't really have any good names to suggest, but I thought I would bring it up. 
If I'm reading Nils' configs properly, it looks like he write configs for each of his LS-specific parts individually, (that is, per part) then puts the code for each kind of LS mod in those configs. Right now, the Carbon Extractor isn't set to be in game with USI-LS. I'm wondering: would it make sense to make a fork of KPBS, make commits to it as we go, then make a pull request when we're done?

**Comment by DanStaal** [comment]
I was actually thinking of calling it an air purifier or air cycler.  (I don't want to call it an air filter, because that could get confusing for support.)

In theory we probably should make a fork - but it'd mess up my workflow.  ;)  I'm essentially keeping the 'USI-LS' folder as limited version of his LifeSupport folder, with the thought being that it should merge in fairly clean.

**Comment by Merkov** [comment]
Yeah, I can absolutely see it messing up workflow. So when the time comes, do you want break up our USI-LS file into his part configs, or would you make a pull request removing USI-LS patches from the individual parts and put in our USI_LS file as one patch?

**Comment by DanStaal** [comment]
The KPBS_MM_USI_LS.cfg file is a direct copy of one of his configs.  (It's in ModSupport/Configs/LifeSupport.)  We'll merge the changes.  It only covers life support on parts that exist without life support mods installed.

The stand-alone files will need to be merged into the individual parts as needed.

**Comment by Merkov** [comment]
Oh, okay. Man, I am having a hard time following KPBS's file structure. So that's why you've created the extra file for the Algae Container; it will have to be manually merged with the KPBS Algae Container config file.

**Comment by Merkov** [comment]
Okay, I made a Carbon Extractor file. Let me know what you think.

**Comment by DanStaal** [comment]
Made a few minor tweaks.  (Config files *need* to have the extension .cfg...)  But looks decent.

I suspect the techrequired line isn't going to work, but we can try it.  ;)

**Comment by Merkov** [comment]
It actually seems to have worked. I added it into a fresh save without CTT and it was in the survivability node. Added CTT, and it was put into the recycling node. 
I _promise_ I knew that it needed the .cfg extension. I'm just dumb. 
I have to say, that's a nifty looking model. I'll be glad to have it included.

**Comment by DanStaal** [comment]
Did it actually have a recycler module?  (In my test load it didn't.)

Also, for some reason I'm getting the same model as the recycler.  Hmm.

**Comment by Merkov** [comment]
I actually forgot to look for the recycling module. I did have a different model, though. 

What I did was copy the text config I wrote and pasted it at the end of Nils' config. I also added a |USILifeSupport to the :NEEDS at the beginning of the config, since by default the Carbon Exractor doesn't appear with USI-LS. The model is similar to the recycler, but definitely different, especially from the side.

**Comment by Merkov** [comment]
I just realized that I should probably post the ENTIRE config file. If Nils updates any part of the config before we release, we'll have to deal with that. 
In a game without CTT, you should see both the Recycler and the Carbon Extractor (renamed to the Air Refresher) in the survivability tech node. I can see the module in the right click menu from there.

**Comment by DanStaal** [comment]
I have it as a separate part - a *new* config file.

**Comment by Merkov** [comment]
Oh! That looks like a much cleaner way to do things.

**Comment by DanStaal** [comment]
Heh.  That's really the way Nils does things anyway - If it's got a different name, it's a separate config - even if it's sharing the model.

**Comment by DanStaal** [comment]
I'm thinking we may want to move this one to Basic Science - a very early tier recycler.  Of course, it's not much use until the racks come later...

**Comment by Merkov** [comment]
Having it early tier sounds good. I can't remember when you get the first racks.

**Comment by DanStaal** [comment]
Hmm.  I'm not actually seeing this at all with our current configs.

**Comment by DanStaal** [comment]
Ok, found and fixed the issue with it not showing up.  Looks to be working now.
