### ISSUE TITLE
Greenhouse Container

### ISSUE THREAD

**Issue by DanStaal** [DanStaal/DStaal_UKS_KPBS_Addons#20]
Config update needed.

Habitation/Recycling Info:

| Part                     | PartName                                   | Mass    | Volume   | Seats | Months | Multiplier | EC/s                  | Recycler % | Spreadsheet Approved? |
|:-------------------------|:-------------------------------------------|---------|----------|-------|--------|------------|-----------------------|------------|-----------------------|
| Greenhouse Container     | KKAOSS\_LS\_container\_greenhouse          | 0.5     | 2.4      | 0     | n/a    | n/a        | n/a                   | n/a        | no                    |

**Comment by Merkov** [comment]
Copying over my chart from the LS Info issue: 

Part|PartName|Mass|Volume|Seats|Months|Multiplier|Supplies Rate|EC/s
----|----|----|----|----|----|----|----|----
Greenhouse Container|KKAOSS_LS_container_greenhouse|0.5|2.4|0|n/a|n/a|0.000495|0.99

By my calculations, this puts it almost perfectly in line with the spreadsheet.

**Comment by Merkov** [comment]
Uploaded and updated the config. I changed the stock tech tree node to survivability. That's where Roverdude throws all of his Nom O Matics. I'm tempted to change the CTT node to hydroponics, since that's what it looks like RoverDude wants his 3 NOMs to be in. Looking at his CTT.cfg in USI-LS, though, it looks like he's changed the name of some of his parts (like all of the NOMS) so his CTT config doesn't seem to move them anymore... I think. I'm going to take this up with RD.

**Comment by DanStaal** [comment]
Let's use hydroponics for CTT.  It's the right place, even if RoverDude doesn't have it there yet.  (Especially for this part -  the larger greenhouses or such might be more normal growth systems, but this pretty much has to be hydroponic.)

**Comment by DanStaal** [comment]
Looks to be working.
