### ISSUE TITLE
MK2 Habitat

### ISSUE THREAD

**Issue by DanStaal** [DanStaal/DStaal_UKS_KPBS_Addons#25]
Config update needed.

Habitation/Recycling Info:

| Part                     | PartName                                   | Mass    | Volume   | Seats | Months | Multiplier | EC/s                  | Recycler % | Spreadsheet Approved? |
|:-------------------------|:-------------------------------------------|---------|----------|-------|--------|------------|-----------------------|------------|-----------------------|
| MK2 Habitat              | KKAOSS\_Habitat\_MK2\_g                    | 2.6     | ~14?     | 4     | 30/4   | 1/4        | 0.7                   | n/a        | no                    |

**Comment by Merkov** [comment]
Options using your suggested volume of 18.73 and a crew capacity of 4: 

1) 18 months gives me a suggested volume of 19 and mass of 2.65, which is pretty close. EC/s is 4.5. 

2) Make it 15 months plus a 0.2 x 5 kerbal multiplier (not putting these numbers into the bonus km cell, but the main cells for each) and I get a suggested volume of 18 and mass of 2.775. EC/s is 4. (Useless side note: if I put the months value into the bonus KM cell instead of the normal hab bonus cell, it tells me the volume should be 40, mass should be 0.9, so that's... interesting). 

Lastly, on the MK1, we sort of took balanced hab month numbers, then added the hab bonus on top. (Making the parts technically overpowered, but again, base = comfy) so for comparison:  

3) 17 months plus 0.2 x 5 kerbal multiplier: EC/s of 4.5, volume of 20, mass of 3.025. 
4) 18 months plus 0.2 x 5 kerbal multiplier: EC/s of 4.75, volume of 21, mass of 3.15. 

I'm leaning toward either 3 or 4 myself. Any thoughts?

**Comment by DanStaal** [comment]
I actually lean towards 2.  The hab multipliers will be very powerful once you start putting a station together, so I don't want to overpower things much.

**Comment by Merkov** [comment]
Option 2 sounds good. I made the change to the config.

**Comment by DanStaal** [comment]
Since we're touching this, it might be worth putting in using resources to deploy.  Otherwise looks good.

**Comment by Merkov** [comment]
You want to use resources to deploy it as part of the stage 2 release? What resource would you want to use?

**Comment by DanStaal** [comment]
I see stage 2 as a two-part release: There's the part going to Nils, and the part that stays in this pack that's MKS-specific.  So it would use the standard MKS MaterialKits, SpecializedParts and EC.
