### ISSUE TITLE
MK1 Habitat

### ISSUE THREAD

**Issue by DanStaal** [DanStaal/DStaal_UKS_KPBS_Addons#26]
Config update needed.

Habitation/Recycling Info:

| Part                     | PartName                                   | Mass    | Volume   | Seats | Months | Multiplier | EC/s                  | Recycler % | Spreadsheet Approved? |
|:-------------------------|:-------------------------------------------|---------|----------|-------|--------|------------|-----------------------|------------|-----------------------|
| **MK1 Habitat**          | **KKAOSS\_Habitat\_MK1\_g**                | **1.7** | **10.7** | **3** | **10** | **0**      | **2.5**               | **n/a**    | **yes**               |

**Comment by DanStaal** [comment]
Configs updated to the above.

**Comment by DanStaal** [comment]
I'm going to re-open while we think about generic multipliers.

**Comment by Merkov** [comment]
Okay, trying to add a 0.2 times multiplier for 4 kerbals does some funny things to the spreadsheet for this part. Now, I knew that the spreadsheet would find this imbalanced, but we decided that it made sense since you're getting a better use of space on the ground, etc. Anyway, by removing the 10 kerbal months and replacing them with a 0.2 times multiplier for 4 kerbals with 10 bonus months, somehow the game decides the part's mass should go way down (0.7) but the volume skyrockets (27). On the other hand, if I don't use the bonus months column and instead use the regular hab column, it just bumps the recommended mass and volume a little bit (up to 12.35 volume and 1.95 t, which isn't bad). Strangely, the EC/s cost is the same for both: 2.7.

My thinking is that adding the 0.2 x 4 multiplier would be good for this part. We'll see how it does with other parts.

**Comment by Merkov** [comment]
Okay, I added the 0.2 x 4 multiplier to the MK1 Hab, and increased the EC usage by 0.2/s.
