### ISSUE TITLE
Science Lab

### ISSUE THREAD

**Issue by DanStaal** [DanStaal/DStaal_UKS_KPBS_Addons#28]
Config update needed.

Habitation/Recycling Info:

| Part                     | PartName                                   | Mass    | Volume   | Seats | Months | Multiplier | EC/s                  | Recycler % | Spreadsheet Approved? |
|:-------------------------|:-------------------------------------------|---------|----------|-------|--------|------------|-----------------------|------------|-----------------------|
| Science Lab              | KKAOSS\_Science\_g                         | 3.55    | ?        | 2     | 0      | 1.25       | 1.2                   | 50/5       | no                    |

**Comment by Merkov** [comment]
Just looking at the science lab for the first time here. I can't make a guess as to the volume right now, but I just decided to try putting in the stock MPL numbers for comparison. The stock MPL also has 2 seats, no multiplier and a 50% recycler for 4 kerbals, which costs 1 EC/s. I put those numbers into the spreadsheet (along with the MPL "Admin Module" value of 5. I still don't fully trust that Admin Module value thingy) and I get a suggested mass of 3.65 and a volume of 20.7. That actually seems like it would fit the stock MPL (RD's spreadsheet says a 2.5 Tundra should have a volume of 18, and the stock MPL has a mass of 3.5, I think?). 
Anyway, that makes me wonder if we should basically just make this a stock MPL clone. On the other hand, since KPBS makes it easy to attach extra greenhouse containers and recycling containers, maybe just making it a hab multiplier would fill a better void? It's easy to spam life support resources, harder to spam hab.

**Comment by DanStaal** [comment]
It should have the same volume as the Mk2 hab, I believe.

And I like the idea of a hab multiplier.  In general, KPBS parts are nice to live in, as they're more like 'houses' than most of the 'retrofitted tubes' that most KSP parts are.

**Comment by Merkov** [comment]
Here's an option for just making the lab a hab multiplier: 

I went with our existing idea of having it affect one more kerbal than it seats, so it affects 3 kerbals. If I make it a 0.5 x multiplier, adding the admin module value plus seating for two, the spreadsheet recommends a volume of 21 (you suggested a little over 18 for the MK2 hab on the forum) and a mass of 4.2. Both of those are a little over, but perhaps close enough when we factor in our comfy base on the ground advantage? This of course doesn't include a recycler, but I think we have enough recyclers at this point...

**Comment by DanStaal** [comment]
Yeah, I think we have enough recyclers.  ;)  Does a slightly smaller multiplier bring the mass/volume down?  I'd rather bring it a bit closer.

**Comment by Merkov** [comment]
Well, this is underwhelming. A 0.1 x 3 kerbal multiplier (EC/s of 0.075) plus the MPL admin module and seating for 2, I get a volume of 18.6 and a mass of 3.6. That's pretty much exactly where we should be...

**Comment by DanStaal** [comment]
Sounds good to me.  A bit small on the multiplier - but you don't really get much recreation space in a lab, which is the main purpose, so I'm good with it.

**Comment by Merkov** [comment]
Done. Man, this computer and Internet Explorer do NOT like Github, but I think I got the change done.
